### ISSUE TITLE
CLI syntax question

### ISSUE THREAD

**Issue by Amphiboly** [AngellusMortis/pyunifiprotect#240]
In assigning multiple doorbell cameras to a chime, I received an error following the outlined syntax:

> \> uprotect chimes 62794a5802a3c003e7009af8 cameras 606f76fa00dbd903e7001197,606f6fee023cd903e700111e
> Invalid camera ID: 606f76fa00dbd903e7001197,606f6fee023cd903e700111e

After replacing the comma with a space, the command completed without error and a test determined that both doorbells now ring the chime.

I have not tested to see if other multiple-device commands have the same parse issue.

Is there a way to assign different chime tones to each camera?

Note that I am running on Windows 11. I see that it is not supported, so feel free to ignore the report.

**Comment by AngellusMortis** [comment]
As mentioned, Windows is not supported. Use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). Only POSIX OSes and sh based shells are supported.
