### ISSUE TITLE
CLI Syntax Problem

### ISSUE THREAD

**Issue by Amphiboly** [AngellusMortis/pyunifiprotect#241]
Exact same problem as in the closed issue 240, recreated on WSL2 Ubuntu 20.04 / Python 3.10.7 /  pyunifiprotect 4.3.3
(uprotect is a wrapper script setting envars).

> $ ./uprotect chimes 62794a5802a3c003e7009af8 cameras 606f76fa00dbd903e7001197,606f6fee023cd903e700111e
> Invalid camera ID: 606f76fa00dbd903e7001197,606f6fee023cd903e700111e
> $ ./uprotect chimes 62794a5802a3c003e7009af8 cameras 606f76fa00dbd903e7001197 606f6fee023cd903e700111e
> $

**Comment by AngellusMortis** [comment]
Looks like it is a documentation issue. Using a space is the correct way to do it. I do know if that was just from upgrading typer that caused it, or I just mistyped the command.
