### ISSUE TITLE
NVR reboot does not work + Add shutdown

### ISSUE THREAD

**Issue by jasonlboggs** [AngellusMortis/pyunifiprotect#246]
I'm experimenting with the NVR reboot endpoint and it seems the current implementation of `reboot_nvr()` does not work.  The correct target path for rebooting the NVR is `{root}/api/system/reboot`.  The only way I was able to accomplish this was by setting the `api_path` property to `/api/` and then executing `r = await protect.api_request("system/reboot", method="post", data={}, raise_exception=False)`.  I have to modify the `api_path` property due to `api_request_raw` prefixing `api_path` to any url passed to this function.  The static value of `/proxy/protect/api/` does not work for the reboot endpoint.  By setting `api_path` to `/api/`, the NVR successfully reboots.  Also, the NVR returns code `204`.  While this is the expected return (as confirmed from dev tools on Chrome), the `api_request_raw` function should be modified to allow for code `204 (No Content)`.

As an enhancement request, could you add a `shutdown_nvr()` function?  I believe the path for this is `{root}/api/system/shutdown`.  We occasionally get power outages where I live and I'd like to build some automation to shut down the NVR and preserve backup power for critical operations such as modem and router.

Thank you!

**Comment by AngellusMortis** [comment]
The System API is different from the Protect API. It is explicitly out of scope in [accordance to the README](https://github.com/AngellusMortis/pyunifiprotect#todo--planned--not-implemented). 

I do plan to eventually split out the UniFi OS console login into another package and make a UniFi OS package.
