### ISSUE TITLE
get_camera_snapshot is only returning a 360p image

### ISSUE THREAD

**Issue by cyberpower678** [AngellusMortis/pyunifiprotect#268]
I suddenly started getting 360p images when I was getting 1080p.  I thought it was an issue with protect, but when I requested the endpoint in a browser, I get the full 4K image.  Can you please figure out what is happening here?

**Comment by sagaland93** [comment]
Same issue here

**Comment by AngellusMortis** [comment]
Discussion with more details: https://github.com/AngellusMortis/pyunifiprotect/discussions/345
