### ISSUE TITLE
Toggling "Color Night Vision" on G5 Pro cameras with "Vision Enhancer"

### ISSUE THREAD

**Issue by cmsimike** [AngellusMortis/pyunifiprotect#303]
Hi,

I just picked up a couple G5 Pros with Vision Enhancers and going it doesn't *seem* possible to control whether or not I can enable "Color night vision"
<img width="342" alt="image" src="https://github.com/AngellusMortis/pyunifiprotect/assets/204378/cdf8bc1b-4297-4838-96d1-36b282b53d18">

With the vision enhancer attached, a flood light turns on when the camera detects motion and it's dark. This settings enables or disables that feature.
It would be ideal if I can manually turn the light on/off but that functionality doesn't seem to exist :(

**Comment by AngellusMortis** [comment]
Please provide sample output for your Protect instance: https://angellusmortis.github.io/pyunifiprotect/v4.10.x/dev/#generating-test-data

**Comment by cmsimike** [comment]
Will do - of me walking in front of the camera to turn on the flood light or toggling the checkbox in the UI?

**Comment by cmsimike** [comment]
I forgot to mention it in here but I sent the info dumped via email a while ago.

**Comment by cmsimike** [comment]
Looks like some support already exists for this, so maybe I just don't know how to toggle it. I'll keep looking.
`    is_color_night_vision_enabled: Optional[bool] = None`
