### ISSUE TITLE
Please add support for new event types intoduced in Protect 2.9.16

### ISSUE THREAD

**Issue by RaHehl** [AngellusMortis/pyunifiprotect#305]
Hi,

Ui introduced new event types in the latest EA Protect version.

See also https://github.com/home-assistant/core/issues/99707

If i had to to guess i would say it's  "door access detection" what's new.

So please add the new event type here https://github.com/AngellusMortis/pyunifiprotect/blob/master/pyunifiprotect/data/types.py

**Comment by RaHehl** [comment]
maybe they changed more, i'm note sure but it looks like they changed "modelKey" to "modelkey".

If i Modify my convert.py from model = ModelType(data["modelKey"]) to model = ModelType(data["modelkey"]) i'm able to generate sampledata

**Comment by Dopiz** [comment]
May also need to change the key from `modelKey` to `modelkey`

**Comment by sreknob** [comment]
FYI, integration starts again and works fine in EA version 2.9.20.
The only constant is change...

Log now indicate:
```
Logger: pyunifiprotect.utils
Source: components/unifiprotect/data.py:134
First occurred: 9:38:05 AM (20 occurrences)
Last logged: 9:38:05 AM

Unknown video mode: sport
Unknown video mode: slowShutter
```
