### ISSUE TITLE
Doorbells and smart chimes not found

### ISSUE THREAD

**Issue by Amphiboly** [AngellusMortis/pyunifiprotect#310]
running 4.20.0 (also had same issues with 4.19.0) on Ubuntu

My doorbells (2) are not being enumerated. I had two G4 doorbells running with no problem on earlier versions (using unifi-protect-backup to offload image files). One doorbell died, taking down the transformer with it. This week I received a G4 Pro to replace the failed G4, and a new transformer. All is working from the Unifi Protect perspective, but neither the old doorbell nor the new one appears in the output of `unifi-protect cameras` or under the shell interface using `for camera in protect.bootstrap.cameras.values():`

I also do not see the smart chime enumerated (using `for camera in protect.bootstrap.chimes.values():`).

Please advise. Happy to provide additional information.

-- 
Rik

**Comment by AngellusMortis** [comment]
> Please advise. Happy to provide additional information.

You did not provide any information. What version of Python are you using? Where are you running Protect? What version of UniFi OS and Protect do you have?

**Comment by Amphiboly** [comment]
Python 3.10.12. Protect 2.8.35 is running on a UCK G2 Plus v3.1.16.

**Comment by AngellusMortis** [comment]
Can you provide a copy of your [anonymized test data](https://angellusmortis.github.io/pyunifiprotect/v4.20.x/dev/#generating-test-data)?

**Comment by Amphiboly** [comment]
[test.zip](https://github.com/AngellusMortis/pyunifiprotect/files/12602116/test.zip)

This should have at least one camera event, a doorbell motion detection, a doorbell ring, and a chime ring.

**Comment by AngellusMortis** [comment]
User only has permission to see 4 cameras. A G3 Instant, a G3 Flex and 2x G4 Bullets. If you want the user to have access to a doorbell or chimes, you need to give them permissions to them. Configuring user permissions is something you can get help with from the Ubiquiti community and largely out of scope here since I can pyunifiprotect cannot do anything with data it never gets.

**Comment by Amphiboly** [comment]
Thank you for the quick turnaround. All fixed now. The odd thing is that one of the doorbells was previously operational under pyunifiprotect.
