### ISSUE TITLE
unifi-protect cameras save-video exporting empty file

### ISSUE THREAD

**Issue by adkandari** [AngellusMortis/pyunifiprotect#312]
Not sure what I am doing wrong, but save-video cli command is exporting a blank corrupt mp4 file

unifi-protect cameras <id> save-video export.mp4 2023-09-29T08:11:31 2023-09-29T08:13:04

the snapshot one works perfectly.

I have also checked the timestamp video exists in the HDD, and I can export it from the web UI.

**Comment by AngellusMortis** [comment]
You command is invalid. No camera ID. 

If you just forgot to include the ID in your example command, make sure you also provide the version of pyunifiprotect, video of UniFi OS, type of UniFi OS console and version of UniFi Protect.

**Comment by AngellusMortis** [comment]
Closing due to lack of response.
