### ISSUE TITLE
Optional backup dependencies cause main cli fail if not installed

### ISSUE THREAD

**Issue by jimfenton** [AngellusMortis/pyunifiprotect#313]
When installing in a virtual environment on MacOSX, there were dependencies that aren't mentioned in the documentation, and require installation via pip:

asyncify
av
sqlalchemy

All three of these were required to get even the --help option to work.

**Comment by AngellusMortis** [comment]
They are supposed to be optional and should only be required for the `backup` subcommand. You can use the `backup` extra to get them installed.
