### ISSUE TITLE
Heads up 3.2.12 is going to break Pyunifiprotect again

### ISSUE THREAD

**Issue by cyberpower678** [AngellusMortis/pyunifiprotect#355]
Just got the EA update and it won’t work with the current version of pyunifiprotect.

**Comment by kudos** [comment]
@AngellusMortis any chance you could cut a release for this so we can update home-assistant to use it? Anyone who upgraded and then downgraded Unifi Protect is getting caught by it too. Thanks!

**Comment by AngellusMortis** [comment]
No. pyunifiprotect has not been updated to fully support the new version yet so there will be no new version yet.

Also, HA explictly tells you to not use EA versions. This is why. I would not be able to get everything ready and done before the beta ended anyways.

**Comment by starsoccer** [comment]
Bump on this? Just got updated and my integration broke. Appreciate you working on adding this and happy to test a beta release if you need any testers

**Comment by AngellusMortis** [comment]
pyunifiprotect _and_ Home Assistant has supported 3.0.x for almost a week now. Seriously, stop fucking spamming me. If you want your Home Assistant fixed, start spamming Frenck and paulus, as I have absolutely not control over when they decide to release 2024.3.2.
