### ISSUE TITLE
_process_nvr_update updating bootstrap.nvr with the wrong nvr data

### ISSUE THREAD

**Issue by UmbrellaCodr** [AngellusMortis/pyunifiprotect#368]
I'm not familiar with this code base; but would be happy to push a pull request if requested.

my HomeAssistant is not able to browse media source / events and continuously gets the following error in the UI:
```
Unexpected identifier: <nvr_id.stacked>:browse:<camera>
```
I have 2 NVR pro's stacked. 

I thought there was a bug in the media source; but it appears that the following call stack overwrites my primary nvr information with the stacked nvr information.
ProtectData -> async_setup() -> async_refresh() -> async_connect_ws(force) -> _process_nvr_update()

```
ProtectData->api.bootstrap.nvr
```

I think we need some sort of check before swapping the information during the _process_nvr_update().

here is a suggested fix:
```python
diff --git a/pyunifiprotect/data/bootstrap.py b/pyunifiprotect/data/bootstrap.py
index 97f021c..5c666fd 100644
--- a/pyunifiprotect/data/bootstrap.py
+++ b/pyunifiprotect/data/bootstrap.py
@@ -428,6 +428,7 @@ class Bootstrap(ProtectBaseObject):
         packet: WSPacket,
         data: dict[str, Any],
         ignore_stats: bool,
+        id: str = None,
     ) -> Optional[WSSubscriptionMessage]:
         if ignore_stats:
             _remove_stats_keys(data)
@@ -442,6 +443,9 @@ class Bootstrap(ProtectBaseObject):
             self._create_stat(packet, [], True)
             return None
 
+        if id and not self.nvr.id == id:
+            return None
+
         old_nvr = self.nvr.copy()
         self.nvr = self.nvr.update_from_dict(deepcopy(data))
 
@@ -569,7 +573,9 @@ class Bootstrap(ProtectBaseObject):
 
             if action["action"] == "update":
                 if action["modelKey"] == ModelType.NVR.value:
-                    return self._process_nvr_update(packet, data, ignore_stats)
+                    return self._process_nvr_update(
+                        packet, data, ignore_stats, action["id"]
+                    )
                 if (
                     action["modelKey"] in ModelType.bootstrap_models()
                     or action["modelKey"] == ModelType.EVENT.value

```
The above patch addresses my home assistant issue; but it's not clear if that's the correct fix or not.

**Comment by AngellusMortis** [comment]
If you want to submit your patch you can, however, this is not a HA support repo so I am going to close the issue. You may open a new issue if you like that is not so HA specific.

**Comment by UmbrellaCodr** [comment]
I'll open a new issue as this is not HA Core specific.
