### ISSUE TITLE
_process_nvr_update updating bootstrap.nvr with the wrong nvr data (when the NVR's are stacked)

### ISSUE THREAD

**Issue by UmbrellaCodr** [AngellusMortis/pyunifiprotect#369]
When processing events from the websocket the nvr.stacked events cause the bootstrap.nvr information to get overwritten with the nvr.stacked data; the bootstrap.nvr object should be the primary nvr and should not be updated with data from the stacked unit.

```python
diff --git a/pyunifiprotect/data/bootstrap.py b/pyunifiprotect/data/bootstrap.py
index 97f021c..5c666fd 100644
--- a/pyunifiprotect/data/bootstrap.py
+++ b/pyunifiprotect/data/bootstrap.py
@@ -428,6 +428,7 @@ class Bootstrap(ProtectBaseObject):
         packet: WSPacket,
         data: dict[str, Any],
         ignore_stats: bool,
+        id: str = None,
     ) -> Optional[WSSubscriptionMessage]:
         if ignore_stats:
             _remove_stats_keys(data)
@@ -442,6 +443,9 @@ class Bootstrap(ProtectBaseObject):
             self._create_stat(packet, [], True)
             return None
 
+        if id and not self.nvr.id == id:
+            return None
+
         old_nvr = self.nvr.copy()
         self.nvr = self.nvr.update_from_dict(deepcopy(data))
 
@@ -569,7 +573,9 @@ class Bootstrap(ProtectBaseObject):
 
             if action["action"] == "update":
                 if action["modelKey"] == ModelType.NVR.value:
-                    return self._process_nvr_update(packet, data, ignore_stats)
+                    return self._process_nvr_update(
+                        packet, data, ignore_stats, action["id"]
+                    )
                 if (
                     action["modelKey"] in ModelType.bootstrap_models()
                     or action["modelKey"] == ModelType.EVENT.value
```

**Comment by AngellusMortis** [comment]
I do not have a stacked setup, so I cannot reproduce this. Can you [generate data](https://angellusmortis.github.io/pyunifiprotect/latest/dev/#updating-requirements) from your console and provide me with the NVR object(s) and some Websocket events for the NVR that are causing the overwrite?

**Comment by UmbrellaCodr** [comment]
```
unifi-protect --no-verify generate-sample-data -o /tmp/dump
```
[dump.tgz](https://github.com/AngellusMortis/pyunifiprotect/files/14736892/dump.tgz)

The first packet that causes the nvr object to get replaced is this one:
```
{'ports': {'ump': 7449, 'http': 7080, 'https': 7443, 'rtsp': 7447, 'rtsps': 7441, 'rtmp': 1935, 'devices_wss': 7442, 'camera_https': 7444, 'live_ws': 7445, 'live_wss': 7446, 'tcp_streams': 7451, 'playback': 7450, 'camera_events': 7551, 'stacking': 7600, 'tcp_bridge': 7888, 'ai_feature_console': 7086, 'ucore': 11081, 'piongw': 7777, 'discovery_client': 0, ...}, 'hosts': [IPv4Address('10.0.0.241')], 'doorbell_settings': {'default_message_text': 'WELCOME', 'custom_messages': [...], 'default_message_reset_timeout': datetime.timedelta(seconds=60)}}
```

10.0.0.241 is my stacked unit; where 10.0.0.240 is my primary unit.

**Comment by AngellusMortis** [comment]
If you poke through the WS messages (you can re-run it with `--actual` to get real values) are you seeing messages for other devices from the other NVR? Like do you get messages for the cameras and stuff too?

**Comment by UmbrellaCodr** [comment]
I see all cemera's messages; none of them have the "nvr" id's in them.  One observation I see in the `ws_messages.json` is that for most updates for the stacked nvr include a `name` field of `nvrStacking.updates` and a `recordId` of `different.id` (very close to the primary but the first few bytes differ, but the same for all actions)

```json
       "raw": ...,
       "action": {
            "action": "update",
            "newUpdateId": "ecd4ad29-a7ff-4a79-8dbc-5116ff1fa190",
            "modelKey": "nvr",
            "id": "stacked.id",
            "name": "nvrStacking.updates",
            "recordModel": "nvr",
            "recordId": "different.id",
            "type": "event",
            "timestamp": 1711326917648
        },
        "data": {
            "systemInfo": {
                "cpu": {
                    "averageLoad": 8.4,
                    "temperature": 69
                },
                "memory": {
                    "available": 5235012,
                    "free": 87460,
                    "total": 8162788
                },
```

This one feels like an outlier; which matches the payload above (my first payload that overwrites the nvr); where does the id come from that is in the action?
```json
        "raw": ...,
        "action": {
            "action": "update",
            "newUpdateId": "08682b32-cd86-4e55-bd16-ef1921ae105c",
            "modelKey": "nvr",
            "id": "stacked.id",
            "recordModel": "nvr"
        },
```

I get a bunch of updates for the primary one as well:
```json
        "raw": ...,
        "action": {
            "action": "update",
            "newUpdateId": "d81d9251-a5c2-425c-b2c7-3ff47db95016",
            "modelKey": "nvr",
            "id": "primary.id",
            "_body": {
                "systemInfo": {
                    "cpu": {
                        "averageLoad": 15.4,
                        "temperature": 73
                    },
                    "memory": {
                        "available": 4866464,
                        "free": 90652,
                        "total": 8162788
                    },
```

**Comment by AngellusMortis** [comment]
What I am trying to understand is it if  _only_ posts messages for the _other_ NVR or if it also posts messages for the _other_ cameras as well. Do I need to filter out messages for other models? Or just the NVR?

**Comment by UmbrellaCodr** [comment]
I don't think you need to do anything with the camera's.  All my camera's are working as expected in Home Assistant; And I have them re-exported to HomeKit; That is all working fine. I see 1 copy of all 28.  So I have 13-14 cameras on each NVR; 

When I first started looking at this last night the bug in home assistant is when it attempts to access the nvr from the Media Source the hass object starts out with the correct `.bootstrap.nvr.id` for the primary id; but then during the "async setup" it forces an update which refreshes all objects from the websocket; which causes the `.bootstrap.nvr.id` to change and throws an exception in the HomeAssistant state when doing a data source lookup; but since the nvr.id changed it no longer matches the data source and throws the exception.  It took me a bit to narrow down what was causing the nvd.id to change.

I am not exactly sure how to precisely answer your question above but if you give me guidance I would be happy to provide the information.

**Comment by AngellusMortis** [comment]
@UmbrellaCodr Can you test the PR: https://github.com/AngellusMortis/pyunifiprotect/pull/371? Let me know if it works.

**Comment by UmbrellaCodr** [comment]
Yes give me 12 or so hours to get home and off work.

**Comment by UmbrellaCodr** [comment]
Your pull request addressed my current issue;  I have a question don't know if this is the correct forum to ask the question or not;

In reading your code I noticed the following: (happy to file a new issue as well, if you agree)

Given the following:
```
    protect = ProtectApiClient(host, port, username, password, verify_ssl=False)
    await protect.update()  # this will initialize the protect .bootstrap and open a Websocket connection for updates
    bootstrap = await protect.get_bootstrap()
```

Home Assistant is using the above to initialize it's state; I noticed some state is getting stripped during:
```
async def get_bootstrap(self) -> Bootstrap:
data = await self.api_request_obj("bootstrap")
```

This data object actually has an array of 2 nvr objects in there; but looking at the resulting bootstrap object the `nvrs` is stripped out of the resulting bootstrap obj. 

<img width="162" alt="image" src="https://github.com/AngellusMortis/pyunifiprotect/assets/95475404/4eb1eaf8-55d1-485c-9c4d-474c7cf4d782">

I wonder if it makes sense to keep both `nvrs` object here and update the appropriate one.

**Comment by AngellusMortis** [comment]
The `nvrs` object does not get return at all if you do not have a stack. The main goal of that PR is just to fix your issue, which is the current NVR getting overwritten by other NVRs in the stack. I can use your data to probably add support for `nvrs` objects, but that would not be much use unless I set up a second NVR myself (or someone else does) so I can figure out all of the APIs to manage them.
