### ISSUE TITLE
await outside function - Python - 

### ISSUE THREAD

**Issue by xenia-09A** [AngellusMortis/pyunifiprotect#375]
Hello Im getting  the below error

and also pycharm is not happy with await per the current example on the Git project

protect = ProtectApiClient(host, port, username, password, verify_ssl=False)

# this will initialize the protect .bootstrap and open a Websocket connection for updates
await protect.update()

error:

(<class 'SyntaxError'>, SyntaxError("'await' outside function", ('/U[scrubbed], 12, 1, 'await protect.update()\n', 12, 23)), <traceback object at 0x101f3ef80>)

**Comment by AngellusMortis** [comment]
https://docs.python.org/3/library/asyncio.html

**Comment by xenia-09A** [comment]
@AngellusMortis  thank you so much I got the names of the cameras as a test!
thank you again
