### ISSUE TITLE
Is it possible the G5 Turret Ultra is detected as having a package camera?

### ISSUE THREAD

**Issue by chmac** [AngellusMortis/pyunifiprotect#403]
I have an issue in home assistant, which uses this package. (Report is here: https://github.com/home-assistant/core/issues/119218)

I'm not sure what's going on, but somehow home assistant seems to believe that my G5 Turret Ultra has a package camera. It's calling `get_pacakge_snapshot()` but the camera doesn't support package snapshots and so pyunifiprotect, quite reasonably, generates an error.

I just installed home assistant today, and python is not my language of choice, I'm not sure if somehow the G5 Turret Ultra, being a fairly new camera, might be detected as having a package camera. I've tried reading through the code here to figure out how this works, but all I found was something about the FPS rate being < 2. 🤷‍♂️ 

If you have any advice or input, I'd be grateful.

Thanks for this package, it's awesome that I can see my (other) unifi cameras in home assistant and this code makes that possible. 🧡

**Comment by AngellusMortis** [comment]
Repo has nothing to do with Home Assistant.

**Comment by chmac** [comment]
Apologies if my question wasn't clear. I'm asking if this package detects the G5 Turret Ultra as having a package camera when in fact it does not.

**Comment by AngellusMortis** [comment]
If you have a question about how the library works, you can make a [dicussion](https://github.com/AngellusMortis/pyunifiprotect/discussions). If you think there is an issue with the library, you will need to make a new issue with steps to reproduce that do not involve Home Assistant.
